# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Adir_cliente.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets, uic

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(796, 448)
        MainWindow.setStyleSheet("background-color:rgb(222, 255, 252)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(219, 160, 321, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(219, 60, 321, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.dni = QtWidgets.QLabel(self.centralwidget)
        self.dni.setGeometry(QtCore.QRect(40, 61, 31, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dni.setFont(font)
        self.dni.setObjectName("dni")
        self.fnacimiento = QtWidgets.QLabel(self.centralwidget)
        self.fnacimiento.setGeometry(QtCore.QRect(40, 343, 122, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.fnacimiento.setFont(font)
        self.fnacimiento.setObjectName("fnacimiento")
        self.direccion = QtWidgets.QLabel(self.centralwidget)
        self.direccion.setGeometry(QtCore.QRect(40, 287, 94, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.direccion.setFont(font)
        self.direccion.setObjectName("direccion")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(219, 270, 321, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(219, 390, 321, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.apellidos = QtWidgets.QLabel(self.centralwidget)
        self.apellidos.setGeometry(QtCore.QRect(40, 174, 92, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.apellidos.setFont(font)
        self.apellidos.setObjectName("apellidos")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 400, 136, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.nombre = QtWidgets.QLabel(self.centralwidget)
        self.nombre.setGeometry(QtCore.QRect(40, 117, 71, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nombre.setFont(font)
        self.nombre.setObjectName("nombre")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(219, 220, 321, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(219, 330, 321, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(219, 110, 321, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.genero = QtWidgets.QLabel(self.centralwidget)
        self.genero.setGeometry(QtCore.QRect(40, 230, 68, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.genero.setFont(font)
        self.genero.setObjectName("genero")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(570, 230, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(159, 255, 117);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Añadir Cliente"))
        self.dni.setText(_translate("MainWindow", "DNI"))
        self.fnacimiento.setText(_translate("MainWindow", "F.NACIMIENTO"))
        self.direccion.setText(_translate("MainWindow", "DIRECCIÓN"))
        self.apellidos.setText(_translate("MainWindow", "APELLIDOS"))
        self.label_8.setText(_translate("MainWindow", "CODIGO POSTAL"))
        self.nombre.setText(_translate("MainWindow", "NOMBRE"))
        self.comboBox.setItemText(0, _translate("MainWindow", "MASCULINO"))
        self.comboBox.setItemText(1, _translate("MainWindow", "FEMENINO"))
        self.genero.setText(_translate("MainWindow", "GÉNERO"))
        self.pushButton_2.setText(_translate("MainWindow", "AÑADIR"))
        self.label.setText(_translate("MainWindow", "INGRESE LOS DATOS Y PULSE AÑADIR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

